### ISSUE TITLE
Does the method `undirPartitioningLibrary` support fixing the acyclicity?

### ISSUE THREAD

**Issue by zark721** [GT-TDAlab/dagP#4]
I am reading the code of a method `void **undirPartitioningLibrary**(dgraph* G, idxType* part, const MLGP_option opt, int seed)` located in src/common/undirPartitioning.c.
The function's comment says that `This function partition a graph using Metis or Scotch **with fixing the acyclicity**`. But there is no code for fixing acyclicity problems. To my understanding, Metis is about undirected graph partitioning so doesn't support fixing acyclicity. I have little knowledge of  SCOTCH. 
Is the function's comment wrong or am I wrong?
Thanks for your help in advance.
![image](https://github.com/GT-TDAlab/dagP/assets/44084756/5bd11ff6-3a7b-46ea-812b-534b2610db84)

**Comment by myozka** [comment]
Hello,
You are correct. The comment is misleading here. Fixing acyclicity is done separately after the call to `undirPartitioningLibrary` function in `undirAcyclicBisectionLibrary`. This function is only a driver for Metis and Scotch partitioners.
