### ISSUE TITLE
How do we partition a graph whose weights are vectors?

### ISSUE THREAD

**Issue by halfmanli** [GT-TDAlab/dagP#6]
Suppose I have a graph $G(V, E)$, and each node $v \in V$ has a weight denoted as $w =[w_0, w_1, ...]$. One of the constraints is keeping each item in the $w$ balanced. According to Figure 2(d) in this [manual](https://github.com/KarypisLab/METIS/blob/master/manual/manual.pdf), Metis supports partitioning a graph containing multiple weights. After quickly reading the code of dagP, it seems dagP does not support this feature. So is there any simple workaround to achieve this goal? I really appreciate your help.

**Comment by myozka** [comment]
Unfortunately, currently, there is no multi-constraint support in dagP and there is no simple workaround that would work for the general case.
As an alternative, you might consider finding a way to combine the different weights or select a representative for your specific use case. I hope this option proves helpful. Best wishes as you move forward with your work!
